### ISSUE TITLE
Add case-insensitive table matchers?

### ISSUE THREAD

**Issue by shoe** [mojotech/dill#17]

**Comment by adsteel** [comment]
I think always downcasing #to_table might force developers to downcase their tables in the long run, but I think it will be difficult and frustrating in the meantime. Forcing #to_table to lower case essentially makes the table matching case insensitive, but without the developer's awareness. A case-insensitive table matcher seems like a good idea, so that the developer can be more aware of the behavior.

PR opened here https://github.com/mojotech/dill/pull/115 and further discussion welcome.

**Comment by adsteel** [comment]
Fulfilled with https://github.com/mojotech/dill/pull/121
